name: Dispatch Event

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Dispatch Event To Another Repository
        env:
          BLOG_ACTION_TOKEN: ${{ secrets.BLOG_ACTION_TOKEN }}
          EVENT: theme-push
          OWNER: lushihuan
          REPO: lushihuan.github.io
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${BLOG_ACTION_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
          -d '{"event_type":"${EVENT}"}'
